schema_version: 1

context:
  python_min: 3.10
  version: "0.0.49"

package:
  name: datadepot
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/datadepot/datadepot-${{ version }}.tar.gz
  sha256: 9388cf1dc4caf7240c73f0386e87e2ebd4564b120f77588e94624ba9af9fcc7e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - pandas >=1.5
    - numpy >=1.21

tests:
  - python:
      imports:
        - datadepot
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: The datadepot package provides a collection of datasets used in the book Data Science Foundations and Machine Learning with Python.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/vanraak/datadepot

extra:
  recipe-maintainers:
    - vanraak
