schema_version: 1

context:
  python_min: 3.10
  version: "0.0.51"

package:
  name: datadepot
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/datadepot/datadepot-${{ version }}.tar.gz
  sha256: cd82606c1e40d304368b28d8195c40a63938ce42b753e366cca7d6dd266c4432

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - pandas >=1.5
    - numpy >=1.21

tests:
  - python:
      imports:
        - datadepot
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: The datadepot package provides a collection of datasets used in the book Data Science Foundations and Machine Learning with Python.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/vanraak/datadepot

extra:
  recipe-maintainers:
    - vanraak
