schema_version: 1

context:
  python_min: "3.10"
  version: "0.0.65"

package:
  name: datadepot
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/datadepot/datadepot-${{ version }}.tar.gz
  sha256: 869e94b7547c6d1e253ed60d6936a239e7b606285b1fb2bd9f0ee13f7ca64f33

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - pandas >=1.5
    - numpy >=1.21

tests:
  - python:
      imports:
        - datadepot
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: The datadepot package provides a collection of datasets used in the book Data Science Foundations and Machine Learning with Python.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/vanraak/datadepot

extra:
  recipe-maintainers:
    - vanraak
